baseURL = "https://oystersjp.github.io/"
languageCode = "ja-jp"
DefaultContentLanguage = "ja"
title = "Oysters"
theme = "meghna-hugo"
summaryLength = 10
publishDir = "../public"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

[minify]
  disableSVG = true

# Menu
[menu]
    [[menu.nav]]
    name = "Oystersとは？"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "活動内容"
    URL = "activities"
    weight = 3

    [[menu.nav]]
    name = "作ってきたもの"
    URL = "works"
    weight = 4

# Site params
[params]
home= "Home"
logo = "/assets/images/logo.svg"
logoText = "Oysters"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "若手ものづくり集団 Oysters"
author = "Oysters"
ogTitle = "Oysters"
ogType = "article"
ogUrl = "https://oystersjp.github.io/"
ogImage = "images/slider/hero-area.jpg"

# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = ""
    heading = "Play With Us!!"
    content= "若手ものづくり集団"
    btn = false
    btnText="Explore Us"
    btnURL="#services"

    # oyster
    [params.oyster]
    enable = true
    bgImage = "images/backgrounds/oyster.jpg"

    # bus
    [params.bus]
    enable = true
    bgImage = "images/backgrounds/bus.jpg"

    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"
 