version: 2
jobs:
  build:
    docker:
      - image: zoe3/debian-make
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: which make
          command: which make