version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    environment: 
      TARGET_VERSION: 0.58.3
    steps:
      - checkout
      - run:
          name: Get hugo
          command: 
            echo 'Start installation of Hugo version ${TARGET_VERSION}.'
            curl -L https://github.com/gohugoio/hugo/releases/download/v${TARGET_VERSION}/hugo_${TARGET_VERSION}_Linux-64bit.tar.gz | tar xz -C ./bin/
      - run:
          name: Build html
          command: make build
      - run:
          name: Diff check
          command: ./.circleci/diff-check.sh