name: CI

on:
  push:
    branches: 
    - '**' 
    - '!master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.4]

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code
    - uses: actions/setup-node@v1 
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci     
    - run: npm run build
      name: Run build
    - uses: nwtgck/actions-netlify@v1.0     
      name: deploy to netlify 
      with:
        publish-dir: './out'
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}      


  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.4]

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code
    - uses: actions/setup-node@v1 
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci     
    - run: npm run lint
      name: Run lint