name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '**'
      - '!master'
      - '!gh-pages'

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out repository code
      - uses: ./.github/actions/setup
      - run: npm run build
        name: Run build
      - uses: ./.github/actions/netlify
        id: netlify
        timeout-minutes: 1
        with:
          publish-dir: ./dist
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### :white_check_mark: Deploy preview is ready! 

            | Name | Link |
            |----|----|
            | :hammer: Latest commit | ${{ github.event.pull_request.head.sha }} |
            | :sunglasses: Deploy Preview | ${{ steps.netlify.outputs.netlify-url }} |
          comment_tag: deploy-preview

  lint:
    if: github.event_name == 'push'
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out repository code
      - uses: ./.github/actions/setup
      - run: npm run lint
        name: Run lint
