name: CI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!gh-pages'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out repository code
      - uses: ./.github/actions/setup
      - run: npm run build
        name: Run build
      - uses: nwtgck/actions-netlify@v1.0
        name: deploy to netlify
        with:
          publish-dir: './out'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out repository code
      - uses: ./.github/actions/setup
      - run: npm run lint
        name: Run lint
