name: Visual Regression Testing

on:
  pull_request:
    types: [opened, synchronize]

env:
  screenshots-dir: './.reg/screenshots'

jobs:
  test:
    name: Verify screenshots
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Take expected screenshots from the base branch
        uses: './.github/actions/screenshots'
        with:
          ref: ${{ github.base_ref }}
          path: ${{ env.screenshots-dir }}
      - run: mv ${{ env.screenshots-dir }} .reg/expected

      - name: Take actual screenshots from the current branch
        uses: './.github/actions/screenshots'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.screenshots-dir }}
      - run: mv ${{ env.screenshots-dir }} .reg/actual

      - name: Run visual tests
        continue-on-error: true
        id: vrt
        run: npm run test:vrt
      - uses: ./.github/actions/netlify
        id: netlify
        timeout-minutes: 1
        with:
          publish-dir: ./.reg
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
      - if: ${{ steps.vrt.outcome == 'success' }}
        name: Comment PR if success
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            **✨✨ That's perfect, there is no visual difference! ✨✨**
            You can check [this report](${{ steps.netlify.outputs.netlify-url }}) out here.
          comment_tag: test-report-vrt
      - if: ${{ steps.vrt.outcome == 'failure' }}
        name: Comment PR if failure
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            **reg-suit detected visual differences.**
            Check [this report](${{ steps.netlify.outputs.netlify-url }}), and review them.
          comment_tag: test-report-vrt
