name: Visual Regression Testing
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Japanese fonts
        run: |
          apt-get update
          apt-get purge -y fonts-wqy-zenhei fonts-ipafont-gothic
          apt-get install -y fonts-noto-cjk-extra
          fc-cache -fv
      - uses: ./.github/actions/setup
      - name: Run visual tests
        run: npm run test:vrt
      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: Visual Regression Test Result
          path: .reg/
